apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-01-06T00:15:56Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  uid: 627d7e5e-191c-4d94-9791-01fdf7b428d2
spec:
  clusterIP: 10.96.0.1
  clusterIPs:
  - 10.96.0.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
